[ {
  "id" : "TestSet.model.DelayTS.5.20160321133628119",
  "x" : 516,
  "y" : 353,
  "w" : 90,
  "h" : 161,
  "type" : "DELAY_TSOBJID",
  "inputsHub" : {
    "type" : "IDTSObjectInputConnectionHub",
    "ports" : [ {
      "messageType" : "MANY",
      "buffer" : [ ]
    }, {
      "messageType" : "MINT",
      "buffer" : [ ]
    } ],
    "type" : "IDTSObjectInputConnectionHub"
  },
  "outputsHub" : {
    "type" : "IDTSObjectOutputConnectionHub",
    "ports" : [ {
      "messageType" : "MANY",
      "buffer" : [ ]
    } ],
    "type" : "IDTSObjectOutputConnectionHub",
    "connectedToList" : [ ]
  }
}, {
  "id" : "TestSet.model.DelayTS.2.20160321133627721",
  "x" : 200,
  "y" : 300,
  "w" : 90,
  "h" : 161,
  "type" : "DELAY_TSOBJID",
  "inputsHub" : {
    "type" : "IDTSObjectInputConnectionHub",
    "ports" : [ {
      "messageType" : "MANY",
      "buffer" : [ ]
    }, {
      "messageType" : "MINT",
      "buffer" : [ ]
    } ],
    "type" : "IDTSObjectInputConnectionHub"
  },
  "outputsHub" : {
    "type" : "IDTSObjectOutputConnectionHub",
    "ports" : [ {
      "messageType" : "MANY",
      "buffer" : [ ]
    } ],
    "type" : "IDTSObjectOutputConnectionHub",
    "connectedToList" : [ ]
  }
}, {
  "id" : "TestSet.model.DelayTS.7.20160321133628384",
  "x" : 700,
  "y" : 300,
  "w" : 90,
  "h" : 161,
  "type" : "DELAY_TSOBJID",
  "inputsHub" : {
    "type" : "IDTSObjectInputConnectionHub",
    "ports" : [ {
      "messageType" : "MANY",
      "buffer" : [ ]
    }, {
      "messageType" : "MINT",
      "buffer" : [ ]
    } ],
    "type" : "IDTSObjectInputConnectionHub"
  },
  "outputsHub" : {
    "type" : "IDTSObjectOutputConnectionHub",
    "ports" : [ {
      "messageType" : "MANY",
      "buffer" : [ ]
    } ],
    "type" : "IDTSObjectOutputConnectionHub",
    "connectedToList" : [ ]
  }
}, {
  "id" : "TestSet.model.DelayTS.1.20160321133626840",
  "x" : 100,
  "y" : 300,
  "w" : 90,
  "h" : 161,
  "type" : "DELAY_TSOBJID",
  "inputsHub" : {
    "type" : "IDTSObjectInputConnectionHub",
    "ports" : [ {
      "messageType" : "MANY",
      "buffer" : [ ]
    }, {
      "messageType" : "MINT",
      "buffer" : [ ]
    } ],
    "type" : "IDTSObjectInputConnectionHub"
  },
  "outputsHub" : {
    "type" : "IDTSObjectOutputConnectionHub",
    "ports" : [ {
      "messageType" : "MANY",
      "buffer" : [ ]
    } ],
    "type" : "IDTSObjectOutputConnectionHub",
    "connectedToList" : [ ]
  }
}, {
  "id" : "TestSet.model.SwitchTS.3.20160321133627839",
  "x" : 300,
  "y" : 300,
  "w" : 90,
  "h" : 60,
  "type" : "SWITCH_TSOBJID",
  "inputsHub" : {
    "type" : "IDTSObjectInputConnectionHub",
    "ports" : [ {
      "messageType" : "MANY",
      "buffer" : [ ]
    }, {
      "messageType" : "MANY",
      "buffer" : [ ]
    } ],
    "type" : "IDTSObjectInputConnectionHub"
  },
  "outputsHub" : {
    "type" : "IDTSObjectOutputConnectionHub",
    "ports" : [ {
      "messageType" : "MANY",
      "buffer" : [ ]
    }, {
      "messageType" : "MBANG",
      "buffer" : [ ]
    } ],
    "type" : "IDTSObjectOutputConnectionHub",
    "connectedToList" : [ ]
  }
}, {
  "id" : "TestSet.model.DelayTS.6.20160321133628269",
  "x" : 600,
  "y" : 300,
  "w" : 90,
  "h" : 161,
  "type" : "DELAY_TSOBJID",
  "inputsHub" : {
    "type" : "IDTSObjectInputConnectionHub",
    "ports" : [ {
      "messageType" : "MANY",
      "buffer" : [ ]
    }, {
      "messageType" : "MINT",
      "buffer" : [ ]
    } ],
    "type" : "IDTSObjectInputConnectionHub"
  },
  "outputsHub" : {
    "type" : "IDTSObjectOutputConnectionHub",
    "ports" : [ {
      "messageType" : "MANY",
      "buffer" : [ ]
    } ],
    "type" : "IDTSObjectOutputConnectionHub",
    "connectedToList" : [ ]
  }
}, {
  "id" : "TestSet.model.SwitchTS.4.20160321133627969",
  "x" : 400,
  "y" : 300,
  "w" : 90,
  "h" : 60,
  "type" : "SWITCH_TSOBJID",
  "inputsHub" : {
    "type" : "IDTSObjectInputConnectionHub",
    "ports" : [ {
      "messageType" : "MANY",
      "buffer" : [ ]
    }, {
      "messageType" : "MANY",
      "buffer" : [ ]
    } ],
    "type" : "IDTSObjectInputConnectionHub"
  },
  "outputsHub" : {
    "type" : "IDTSObjectOutputConnectionHub",
    "ports" : [ {
      "messageType" : "MANY",
      "buffer" : [ ]
    }, {
      "messageType" : "MBANG",
      "buffer" : [ ]
    } ],
    "type" : "IDTSObjectOutputConnectionHub",
    "connectedToList" : [ ]
  }
} ]