/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class logic_imagematching_features_pixelbypixel_ImageMatcher */

#ifndef _Included_logic_imagematching_features_pixelbypixel_ImageMatcher
#define _Included_logic_imagematching_features_pixelbypixel_ImageMatcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     logic_imagematching_features_pixelbypixel_ImageMatcher
 * Method:    searchImageInImage
 * Signature: ([III[III)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_logic_imagematching_features_pixelbypixel_ImageMatcher_searchImageInImage
  (JNIEnv *, jobject, jintArray, jint, jint, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
